spring.application.name=Stock_Inventory

server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/stock_inventory_spring
spring.datasource.username=postgres
spring.datasource.password=123

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# File Upload Sizes
#spring.upload-dir=uploads
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.max-file-size=20MB

cloudinary.cloud-name=dmxtjebu5
cloudinary.api-key=179954835527551
cloudinary.api-secret=k7efsPc8s-ZbW1BsdPip9jRuYEc

